The SMART_JaCaMo Team
=====================
:toc:
:toc-placement: preamble
:smart-team: SMART_JaCaMo
:jacamo: JaCaMo
:jason: Jason
:cartago: CArtAgO
:moise: Moise
:eclipse: Eclipse
:junit: JUnit
:jasondtu: Jason-DTU
:akuanduba: Akuanduba-UDESC
:dtg: Dumping to Gather
:tubdai: TUBDAI

This is the source code of the {smart-team} team, one of the teams participating in the https://multiagentcontest.org/2018/[2018 Multi-Agent Programming Contest (MAPC)]. 
In this repository, you will find all the information required to run our code. 

*Have fun!*

// Need some preamble to get TOC:
{empty}

== Our Approach
We used the {jacamo} platform to develop our team of agents. Here, we briefly describe how we applied each programming abstraction of the {jacamo} framework (agent, environment, organisation). 

- *{jason}*: we use {jason} to develop the behaviour of our agents. They are able to reason about the percepts that come from the environment in order to decide their course of action. In our approach, agents may change their intentions depending on the team and environment state;
- *{cartago}*: we use {cartago} to exchange team information between our agents and to interact with the MAPC server;
- *{moise}*: our agents adopt roles in the {moise} organisation which represent particular tasks (builders, gatherers, etc.). We developed our strategies based on these roles, and in this sense, it is easy for our agents to adopt autonomously to a different strategy (i.e., the agents themselves decide to change to a different role). {moise} is also useful to facilitate coordination when multiple agents are required to work together to accomplish a desired task.

For further details about our team implemantation, check out our paper (*coming soon*).

== Prepare the Environment
To start developing and contributing to this repository, open {eclipse}, and select from the toolbar:

> File > Import > Git > Projects from Git > Clone URI

Copy https://github.com/smart-pucrs/mapc2018-pucrs.git and paste it on the URI field.

If you're fond of command line, just copy and paste the following command at your terminal in your desired folder:

> git clone https://github.com/smart-pucrs/mapc2018-pucrs.git

And import this project from local git repository at {eclipse}.

== Run the Code
We use {junit} to run both the server and our {jacamo} code.

To run the simulation with one round, choose your appropriate {junit} test depending on the map you're interested in, and in folder `test/pucrs/agentcontest2018/` right-click ScenarioRun1sim{desired_map}.java file, "Run as", "jUnit Test".

To run the simulation with three rounds, right-click test/pucrs/agentcontest2018/ScenarioRun3sim.java file, "Run as", "jUnit Test".

The server's output is shown on the {eclipse} console. The {jacamo} output is loaded into a separate `gui`. Press `enter` at the server output ({eclipse} console) to start the simulation.

== Watch the Matches
If you'd like to see our matches, follow the links below:

- Versus *{jasondtu}*: https://multiagentcontest.org/2018/replays/?2018-09-24-14-05-06-Contest-2018-1of3[Copenhagen], https://multiagentcontest.org/2018/replays/?2018-09-24-14-05-06-Contest-2018-2of3[Berlin], https://multiagentcontest.org/2018/replays/?2018-09-24-14-05-06-Contest-2018-3of3[S達o Paulo];
- Versus *{akuanduba}*: https://multiagentcontest.org/2018/replays/?2018-09-24-16-26-12-Contest-2018-1of3[Copenhagen], https://multiagentcontest.org/2018/replays/?2018-09-24-16-26-12-Contest-2018-2of3[Berlin], https://multiagentcontest.org/2018/replays/?2018-09-24-16-26-12-Contest-2018-3of3[S達o Paulo];
- Versus *{dtg}*: https://multiagentcontest.org/2018/replays/?2018-09-24-18-31-08-Contest-2018-1of3[Copenhagen], https://multiagentcontest.org/2018/replays/?2018-09-24-18-31-08-Contest-2018-2of3[Berlin], https://multiagentcontest.org/2018/replays/?2018-09-24-18-31-08-Contest-2018-3of3[S達o Paulo];
- Versus *{tubdai}*: https://multiagentcontest.org/2018/replays/?2018-09-25-18-16-09-Contest-2018-1of3[Copenhagen], https://multiagentcontest.org/2018/replays/?2018-09-25-18-16-09-Contest-2018-2of3[Berlin], https://multiagentcontest.org/2018/replays/?2018-09-25-18-16-09-Contest-2018-3of3[S達o Paulo].

To see all the MAPC matches, https://multiagentcontest.org/2018/[click this link] and search for Section *Replays*.
